version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    container_name: keycloak
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KC_DB: dev-file
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - ${KC_PORT}:8080
    volumes:
      - ./data/keycloak:/opt/keycloak/data/h2

  keycloak-config-cli:
    container_name: keycloak-config-cli
    image: adorsys/keycloak-config-cli:latest
    depends_on:
      - keycloak
    volumes:
      - ./keycloak:/config
    environment:
      # cli config
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      IMPORT_FILES_LOCATIONS: '/config/*' 
      SPRING_PROFILES_ACTIVE: dev
      DEBUG: true
      LOGGING_LEVEL_ROOT: debug
      IMPORT_CACHE_ENABLED: false
      IMPORT_VARSUBSTITUTION_ENABLED: true
      # realm config
      KC_REALM_NAME: ${KC_REALM_NAME}
